# Generated by Django 2.0 on 2018-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='', max_length=1000, verbose_name='内容'),
        ),
    ]
