# Generated by Django 2.0 on 2018-08-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '邮件验证码', 'verbose_name_plural': '邮件验证码'},
        ),
    ]
