# Generated by Django 2.0.6 on 2018-07-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='留言信息'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='address',
            field=models.CharField(max_length=100, verbose_name='留言地址'),
        ),
    ]
